/*

  CREATED BY PACKJC
  https://github.com/PackJC/gebsfish
  https://steamcommunity.com/sharedfiles/filedetails/?id=2757509117
  https://discord.com/invite/G8uSGZ8yyf
  Contributions welcome via github

*/

// GENERATED by tools/build_mount_poses.py from the fish models and
// tools/fish_manifest.json. Don't edit by hand: rerun it after adding a
// mountable fish or changing one's model.
//
// How each species hangs on the fish mounts (geb_fishmount.c): the smallest
// mount that holds it (0 small, 1 medium, 2 large), the turn that shows it
// side-on with its head to the viewer's right (yaw about the board's vertical,
// pitch about its long axis, roll about the wall normal, in degrees), the shift
// that centres it on the display point and keeps its back just clear of the
// board (metres: right-to-left, up, out), and its height for placing it in the
// board's clear field.
class GebMountPose {
	int Size;
	float Yaw;
	float Pitch;
	float Roll;
	vector Offset;
	float Height;

	void GebMountPose(int size, float yaw, float pitch, float roll, vector offset, float height) {
		Size = size;
		Yaw = yaw;
		Pitch = pitch;
		Roll = roll;
		Offset = offset;
		Height = height;
	}
}

class GebMountPoses {
	protected static ref map<string, ref GebMountPose> s_Poses;

	// The species' pose. A class that isn't listed (another mod's subclass of a
	// listed fish) takes its nearest listed config parent's pose and size; null
	// for anything else (it hangs as the proxy leaves it, centred on the board's
	// field). Each answer is remembered, misses too.
	static GebMountPose Get(string type) {
		if (!s_Poses) {
			s_Poses = new map<string, ref GebMountPose>();
			Fill();
		}
		GebMountPose pose;
		if (s_Poses.Find(type, pose))
			return pose;
		string cls = type;
		string parent;
		for (int depth = 0; depth < 10; depth++) {
			if (!g_Game.ConfigGetBaseName("CfgVehicles " + cls, parent) || parent == "" || parent == cls)
				break;
			if (s_Poses.Find(parent, pose))
				break;
			cls = parent;
		}
		s_Poses.Set(type, pose);
		return pose;
	}

	protected static void Add(string type, int size, float yaw, float pitch, float roll, float dx, float dy, float dz, float height) {
		s_Poses.Set(type, new GebMountPose(size, yaw, pitch, roll, Vector(dx, dy, dz), height));
	}

	protected static void Fill() {
		Add("Carp", 0, 0, 0, 0, 0.0774, -0.0105, 0.0940, 0.231);
		Add("geb_AlligatorGar", 1, 270, 0, 0, 0.1396, -0.0728, 0.1257, 0.216);
		Add("geb_AmericanBullFrog", 0, 270, 0, 180, -0.0030, 0.0014, 0.0043, 0.122);
		Add("geb_AmericanLobster", 0, 0, 0, 0, 0.1594, 0.0006, 0.0383, 0.412);
		Add("geb_AngelFish", 1, 270, 0, 0, -0.0242, -0.1411, 0.0798, 0.539);
		Add("geb_AngelShark", 2, 270, 0, 270, 0.1580, -0.0919, 0.0744, 1.973);
		Add("geb_AsianSeaBass", 0, 0, 0, 0, 0.0785, -0.0203, 0.0427, 0.141);
		Add("geb_AtlanticBlueMarlin", 2, 270, 0, 0, 0.6093, -0.1480, 0.4676, 1.156);
		Add("geb_AtlanticSailFish", 2, 270, 0, 0, 0.4558, -0.1695, 0.7368, 2.118);
		Add("geb_BarredMuskellunge", 1, 270, 0, 0, 0.0281, -0.0695, 0.1811, 0.344);
		Add("geb_BlackBass", 0, 0, 0, 0, 0.0969, -0.0183, 0.0337, 0.115);
		Add("geb_BlackDevilSnail", 0, 270, 0, 270, 0.0040, -0.0252, 0.0166, 0.051);
		Add("geb_BloodClam", 0, 270, 0, 0, 0.0033, -0.0036, 0.0428, 0.091);
		Add("geb_BlueGill", 0, 0, 0, 0, 0.0270, -0.0180, 0.0290, 0.155);
		Add("geb_BlueJellyFish", 0, 0, 0, 0, 0.0626, 0.0099, 0.0719, 0.185);
		Add("geb_BlueTang", 1, 270, 0, 0, 0.0355, -0.0661, 0.0809, 0.528);
		Add("geb_BowFin", 0, 0, 0, 0, 0.0808, -0.0191, 0.0767, 0.133);
		Add("geb_BrookTrout", 0, 0, 0, 0, 0.0624, -0.0189, 0.0732, 0.169);
		Add("geb_BrownTrout", 0, 0, 0, 0, 0.0624, -0.0189, 0.0732, 0.169);
		Add("geb_CaveCrayFish", 0, 90, 0, 0, 0.0099, -0.0001, 0.0452, 0.069);
		Add("geb_CherrySalmon", 0, 0, 0, 0, 0.1152, 0.0038, 0.0981, 0.212);
		Add("geb_ChinookSalmon", 0, 0, 0, 0, 0.1038, -0.0371, 0.0539, 0.198);
		Add("geb_CutThroatTrout", 0, 0, 0, 0, 0.0576, -0.0183, 0.0783, 0.212);
		Add("geb_EuropeanCrayFish", 0, 90, 0, 0, 0.0099, -0.0001, 0.0452, 0.069);
		Add("geb_EuropeanLobster", 0, 0, 0, 0, 0.1594, 0.0006, 0.0383, 0.412);
		Add("geb_FatHeadMinnow", 0, 90, 0, 0, -0.0098, -0.0062, 0.0332, 0.092);
		Add("geb_FlatHeadCatFish", 1, 270, 0, 0, -0.0442, -0.1286, 0.3034, 0.506);
		Add("geb_FlatHeadMullet", 0, 180, 0, 180, 0.0786, 0.0178, 0.0442, 0.161);
		Add("geb_FloridaCrayFish", 0, 90, 0, 0, 0.0099, -0.0001, 0.0452, 0.069);
		Add("geb_GreatBarracuda", 1, 270, 0, 0, 0.0033, -0.0341, 0.0599, 0.331);
		Add("geb_GreatWhiteShark", 2, 270, 0, 0, -0.0158, -0.1000, 1.3748, 2.501);
		Add("geb_HammerHeadShark", 2, 270, 0, 0, -0.3697, -0.4091, 0.9696, 1.804);
		Add("geb_HumpHeadWrasse", 1, 270, 0, 0, -0.0066, -0.1710, 0.4333, 0.607);
		Add("geb_KingCrab", 1, 180, 0, 270, 0.0157, -0.1253, 0.1593, 0.562);
		Add("geb_LakeSturgeon", 2, 270, 0, 0, -0.1582, -0.0894, 0.4221, 0.620);
		Add("geb_LakeTrout", 0, 0, 0, 0, 0.0576, -0.0183, 0.0783, 0.212);
		Add("geb_LargeHeadHairTailFish", 1, 270, 0, 0, -0.1277, -0.1577, 0.0661, 0.342);
		Add("geb_LargeMouthBass", 0, 0, 0, 0, 0.0896, -0.0207, 0.0791, 0.196);
		Add("geb_LeopardShark", 2, 270, 0, 0, -0.2211, -0.2516, 0.9127, 1.193);
		Add("geb_MahiMahi", 2, 270, 0, 0, 0.0702, -0.0968, 0.2748, 1.389);
		Add("geb_MonongahelaCrayFish", 0, 90, 0, 0, 0.0099, -0.0001, 0.0452, 0.069);
		Add("geb_Muskellunge", 1, 270, 0, 0, 0.0281, -0.0695, 0.1811, 0.344);
		Add("geb_Mussel", 0, 270, 0, 0, -0.0084, -0.0081, 0.0439, 0.108);
		Add("geb_NeoshoBass", 0, 0, 0, 0, 0.1092, -0.0145, 0.0370, 0.158);
		Add("geb_NorthernPike", 1, 270, 0, 0, 0.0281, -0.0695, 0.1811, 0.344);
		Add("geb_NorthernSnakeHead", 1, 270, 0, 0, 0.1469, -0.0815, 0.1981, 0.258);
		Add("geb_PacificBonito", 0, 0, 0, 0, 0.0995, -0.0090, 0.0434, 0.159);
		Add("geb_PacificCod", 1, 0, 0, 0, 0.0682, -0.0173, 0.0817, 0.295);
		Add("geb_RainbowTrout", 0, 0, 0, 0, 0.0576, -0.0183, 0.0783, 0.212);
		Add("geb_RedHeadCichlid", 1, 270, 0, 0, 0.0125, -0.1992, 0.1348, 0.354);
		Add("geb_RedSalamander", 0, 270, 0, 270, -0.0030, 0.0090, 0.0130, 0.032);
		Add("geb_RedSwampCrayFish", 0, 90, 0, 0, 0.0099, -0.0001, 0.0452, 0.069);
		Add("geb_RoughNeckRock", 0, 0, 0, 0, 0.0796, -0.0227, 0.0469, 0.271);
		Add("geb_RustyCrayFish", 0, 90, 0, 0, 0.0099, -0.0001, 0.0452, 0.069);
		Add("geb_Sauger", 0, 0, 0, 0, 0.0665, -0.0163, 0.0893, 0.182);
		Add("geb_Severum", 1, 270, 0, 0, -0.0383, -0.1232, 0.0883, 0.591);
		Add("geb_SiameseTigerFish", 1, 270, 0, 0, 0.0793, 0.0184, 0.0923, 0.417);
		Add("geb_SignalCrayFish", 0, 90, 0, 0, 0.0099, -0.0001, 0.0452, 0.069);
		Add("geb_SlimySculpin", 0, 0, 0, 0, 0.0797, -0.0038, 0.0656, 0.113);
		Add("geb_SmallMouthBass", 0, 0, 0, 0, 0.0738, -0.0123, 0.0304, 0.132);
		Add("geb_SnowCrab", 1, 0, 270, 90, -0.0116, -0.0661, 0.0164, 0.377);
		Add("geb_SockEyeSalmon", 1, 0, 0, 0, 0.1166, -0.0299, 0.0546, 0.264);
		Add("geb_SouthernFlounder", 1, 270, 0, 0, 0.0247, -0.0182, 0.1285, 0.538);
		Add("geb_SpottedMuskellunge", 1, 270, 0, 0, 0.0281, -0.0695, 0.1811, 0.344);
		Add("geb_StarFish", 0, 0, 270, 90, 0.0005, -0.0028, 0.0046, 0.177);
		Add("geb_StripedBass", 0, 0, 0, 0, 0.1042, -0.0191, 0.0258, 0.130);
		Add("geb_SunFish", 0, 0, 0, 0, 0.0270, -0.0180, 0.0290, 0.155);
		Add("geb_TigerMuskellunge", 1, 270, 0, 0, 0.0281, -0.0695, 0.1811, 0.344);
		Add("geb_WallEye", 0, 0, 0, 0, 0.0665, -0.0163, 0.0893, 0.182);
		Add("geb_WhiteBass", 0, 0, 0, 0, 0.0484, -0.0209, 0.0522, 0.258);
		Add("geb_WhiteGrunt", 1, 0, 0, 0, -0.0230, -0.0423, 0.1080, 0.353);
		Add("geb_YellowFinTuna", 0, 0, 0, 0, 0.0741, -0.0174, 0.1031, 0.244);
		Add("geb_YellowPerch", 0, 0, 0, 0, 0.0794, -0.0185, 0.0303, 0.182);
		Add("geb_YellowSnapper", 0, 0, 0, 0, 0.0422, -0.0070, 0.0622, 0.195);
		Add("Mackerel", 0, 0, 0, 0, -0.0587, -0.0167, 0.0297, 0.108);
		Add("Shrimp", 0, 0, 270, 90, -0.0019, -0.0005, 0.0064, 0.111);
		Add("SteelheadTrout", 0, 0, 0, 0, 0.1139, -0.0072, 0.0942, 0.170);
		Add("WalleyePollock", 0, 0, 0, 0, 0.0995, 0.0000, 0.0528, 0.120);
	}
}
