# Prepare the wiki's per-item assets: a trimmed thumbnail for every piece of
# gear, bait and lure, plus its English description, written into docs/ for
# GitHub Pages.
#
#   python tools/build_wiki_items.py [renders_dir]
#
# The gear counterpart to build_wiki_assets.py, and it reuses that script's
# stringtable lookup so item text comes from exactly the same place as fish
# text -- each class's descriptionShort resolved through stringtable.csv, so
# the site always shows what the game shows.
#
# Renders are cropped to the subject and saved as WebP: the source PNGs are
# ~48 MB, which has no business in a git repo for a web page.

import glob
import html
import json
import os
import sys

from PIL import Image

# Same folder, so the fish builder's helpers are importable rather than copied.
from build_wiki_assets import attribute_keys, config_classes, description_keys, english_table

TOOLS = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(TOOLS)
DOCS_IMG = os.path.join(REPO, "docs", "items")
OUT_JS = os.path.join(REPO, "docs", "item-details.js")

MAX_W, MAX_H = 420, 300

# Which tab each render belongs under. Checked in order, first match wins, so
# the specific patterns have to come before the loose ones (SpinnerBait before
# Bait would matter if such a pair existed). Anything unmatched lands in "gear",
# which is the safe default -- it shows up rather than silently disappearing.
CATEGORIES = [
    ("lure",  ("Lure", "SpinnerBait", "SpoonLure", "CurlyTailJig")),
    ("bait",  ("Worm", "Cricket", "GrassHopper", "Grub", "Minnow")),
    ("boat",  ("jonboat",)),
    ("gear",  ()),
]


def categorise(cls):
    for name, needles in CATEGORIES:
        for n in needles:
            if n.lower() in cls.lower():
                return name
    return "gear"


def displayname_keys():
    """classname -> displayName stringtable key, inheritance included."""
    return attribute_keys("displayName")


def prettify(cls):
    """Readable fallback when a class has no displayName: geb_BlueFishKnife -> Blue Fish Knife."""
    import re as _re
    name = cls[4:] if cls.lower().startswith("geb_") else cls
    name = name.replace("_", " ")
    name = _re.sub(r"(?<=[a-z])(?=[A-Z])", " ", name)
    name = _re.sub(r"(?<=[A-Za-z])(?=\d)", " ", name)
    return name.strip().title()


def main():
    renders = sys.argv[1] if len(sys.argv) > 1 else r"C:\Users\ECHO\Desktop\gear_renders"
    if not os.path.isdir(renders):
        print("renders dir not found: %s" % renders)
        return 1
    os.makedirs(DOCS_IMG, exist_ok=True)

    classes = config_classes()
    keys = attribute_keys("descriptionShort", classes)
    names = attribute_keys("displayName", classes)
    table = english_table()

    details, no_desc = {}, []
    for path in sorted(glob.glob(os.path.join(renders, "*.png"))):
        cls = os.path.splitext(os.path.basename(path))[0]

        img = Image.open(path).convert("RGBA")
        bbox = img.getbbox()
        if bbox:
            img = img.crop(bbox)
        img.thumbnail((MAX_W, MAX_H), Image.LANCZOS)
        img.save(os.path.join(DOCS_IMG, cls + ".webp"), "WEBP", quality=86, method=6)

        desc = table.get(keys.get(cls, ""), "")
        if not desc:
            no_desc.append(cls)
        # Escaped because the page injects it with innerHTML.
        label = table.get(names.get(cls, ""), "") or prettify(cls)
        details[cls] = {
            "name": html.escape(label),
            "img": "items/%s.webp" % cls,
            "desc": html.escape(desc),
            "cat": categorise(cls),
        }

    with open(OUT_JS, "w", encoding="utf-8") as fh:
        fh.write("// Generated by tools/build_wiki_items.py -- do not edit by hand.\n")
        fh.write("const ITEMDETAIL = ")
        json.dump(details, fh, ensure_ascii=False, indent=0, sort_keys=True)
        fh.write(";\n")

    total = sum(os.path.getsize(os.path.join(DOCS_IMG, f)) for f in os.listdir(DOCS_IMG))
    counts = {}
    for v in details.values():
        counts[v["cat"]] = counts.get(v["cat"], 0) + 1

    print("images written : %d  (%.1f MB total in docs/items/)" % (len(details), total / 1048576.0))
    print("by category    : %s" % ", ".join("%s %d" % (k, counts[k]) for k in sorted(counts)))
    print("descriptions   : %d of %d have text" % (len(details) - len(no_desc), len(details)))
    if no_desc:
        print("no description : %s" % ", ".join(sorted(no_desc)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
